name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
      - 'k8s/frontend-deployment.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate with AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}/frontend-new:latest ./frontend
          docker push ${{ secrets.ECR_REPOSITORY }}/frontend-new:latest

      - name: Apply Frontend Deployment
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region us-east-1
          kubectl apply -f k8s/frontend-deployment.yaml
